---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-api-v2
  labels:
    app: books-api
    version: v2
    app.kubernetes.io/part-of: books-api
spec:
  selector:
    matchLabels:
      app: books-api
      version: v2
  replicas: 1
  template:
    metadata:
      labels:
        app: books-api
        version: v2
    spec:
      containers:
        - name: books-api
          image: quay.io/redhattraining/3scale-books-api:2
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: books-api-v2
  labels:
    app: books-api
    version: v2
    app.kubernetes.io/component: "books-api"
    app.kubernetes.io/instance: "books-api"
    discovery.3scale.net: "true"
  annotations:
    discovery.3scale.net/port: "80"
    discovery.3scale.net/scheme: "http"
spec:
  selector:
    app: books-api
    version: v2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080